# 第五章 计数资料的统计描述 

日期: 2020-11-22
作者：wxhyihuan

本章节主要时计数资料相关的概念和统计基础，概念的细节比较多，是后面进行离散变量的统计的基础！可以结合树上的案例，更好的理解和引用概念，此处不累述。

计数资料(Enumeration data,Categorical data)，又称定性资料或无序分类资料，是相对于计量资料(Measurement data,又称连续型变量资料，
是指由数值变量的测量值组成的资料)的一个统计概念，是指先将观察单位按其性质或类别分组，然后清点各组观察单位个数所得的资料。
其特点是对每组观察单位主要研究其数量的多少，属非连续性资料。

计数资料常见的数据形式是绝对数，如某病的出院人数、治愈人数等，但绝对数通常不具有可比性，如甲、乙两个医院某病出院人数不同时，
比较两医院该病的死亡人数没有意义，因此需要在绝对数的基础上计算相对数。常用的相对数指标有比、比例和率三种：

1. 当比例与时间有关系时称为率(Rate)，或称强度相对数；
2. 当比的分子是分母的一部分时，称为比例(Proportion)，或称结构相对数；
3. 两个有关指标之比称为比(Ratio)，或称相对比；

## 常用相对数

### 强度相对数

强度相对数也称强度相对指标或强度指标，是指同一时期内两个性质不同而又有一定联系的总量指标之比。它可以反映社会经济现象的强度、密度和普遍程度。
其计算公式为：
$$强度相对数(率)=\frac{某时期内发生某现象的观察单位数}{同时期内可能发生某现象的观察单位总数}\times比例基数$$

比例基数主要是调整通过百分/千分/万分等基数，是计算结果能保留适当有效位数，便于阅读。另外就是要注意，不要忽略公式中时间的范畴，所赋予计算结果是
特定观察时期内的，在结果解释时，这个周期(比如年，月，周，天，时)的含义体现。

### 结构相对数

结构相对数又称比重指标或结构相对指标，是在分组情况下，总体内部各组的数值与总体数值相比计算得到的相对数。它反映总体内部的构成情况，
表明总体中各部分所占比重的大小、一般用百分数表示，计算公式为：
$$结构相对数(比例)=\frac{某一构成部分的观察单位数}{同一事物各组成部分的观察单位总数}\times100\%$$

显然，全体内各组结构相对数的总和应为100%。注意的是，各部分之间是互相影响，某部分的比例既受到自身观察数量变化的影响，
也受到其他部分的观察数量的变化影响。

### 相对比

表示两个有关事物指标之比，常以百分数和倍数表示，用以说明一个指标是另一个指标的百分之几或几倍，其计算公式为：
$$相对比(比)=\frac{指标甲}{指标乙}(\times100\%)$$

指标甲乙可以是绝对数，相对数或平均数。

### 应用相对数的注意点

1. 比例不能代替率，即结构相对数不能代替强度相对数
2. 计算相对数应该有足够的数量
3. 正确计算合计率  对分组资料计算合计表(或称平均率)时，不能简单的由各组率相加或平均而得，要用合计的有关实际数字进行计算
4. 注意资料的可比性在比较相对数时，除了要对比的因素(如不同的药物)，其余的影响因素应尽可能相同或相近。在临床研究和动物实验时，应遵循随机抽样原则进行分组。下列因素可能影响对比组之间的可比性:

+ 观察对象是否同质，研究方法是否相同，观察时间是否相等，以及地区、周围环境、风俗习惯和经 济条件是否一致或相近等。

+ 观察对象内部结构是否相同，若两组资料的年龄、性别等构成不同，可以分别进行同年龄别、同性 别的小组率比较或对总率(合计率)进行[标准化](#率的标准化)后再作比较。

5. 对比不同时期资料应注意客观条件是否相同，例如，疾病报告制度完善和资料完整的地区或年份，发病率可以“升高”；居民因医疗普及，就诊机会增加，或诊断技术提高，也会引起发病率升高”。因此在分析讨论时，应根据各方面情形全面考虑，慎重对待。

6. 样本率(或构成比)的抽样误差不能仅凭数字表面相差大小下结论，而应进行样本率(或构成比)差别的假设检验。

## 率的标准化

当比较的两组资料，其内部各小组率明显不同，且各小组观察例数的构成比，诸如年龄、性别、工龄、病情轻重、病程长短等也明显不同时，
直接比较两个合计率是不合理的。因为其内部构成不同，往往影响 合计率大小。

因此，一种为在两个以上总率(总均数)进行对比时，消除内部构成不同的影响，采用统一的内部构成，分别计算标准化率(Standardized rate)后再做对比的方法，即为标准化方法(Standardization method)，是2014年公布的全科医学与社区卫生名词。标准化法的基本思想是：采用某影响因素的统一标准构成以消除构成不同对合计率的影响，
使通过标准化后的合计率具有可比性。注意的是，它与数据的标准化(Normalization)的概念不同，数据的标准化是将数据按比例缩放，使之落入一个小的特定区间。

### 标准化率的计算

标准化法计算的关键是选择统一的标准构成。常用的标准化方法有直接标准化法和间接标准化法，简称直接法和间接法。根据已有资料的条件，采用不同的方法计算标准化率。如对死亡率的年龄构成标准化，若已知年龄别死亡率，可采用直接法;若只 有总死亡数和年龄别人口数而缺乏年龄别死亡率时，或各年龄组人口数较小，年龄别死亡率不稳定时，宜用间接法。

$N_i$表示标准年龄别人口数，$p_i$为实际年龄别死亡率，N为标准人口众数，选择标准构成的方法通常有三种: 

1. 两组资料中任选组资料的人口数(或人口构成)作为两者的“共同标准”。这种方法适用于直接法。标准化率的计算公式:
$$p'=\frac{\sum N_ip_i}{N}$$

2. 两组资料各部分人口之和组成的人口数(或人口构成)作为两者的“共同标准”。这种方法适用于直接法。标准化率的计算公式:
$$p'=\sum\left(\frac{N_i}{N}\right)p_i$$

3. 另外选用一个通用的或便于比较的标准作为两者的“共同标准”,如采用全国、全省或全地区的数据作为标准，这种方法适用于直接法和间接法。标准化率的计算公式:
$$p'=P\left(\frac{r}{\sum n_iP_i}\right)=P\times SMR$$

$SMR=r/\sum n_iP_i$为标准化死亡比(Standardized mortalitu ratio,SMR)。[标准化死亡比](https://baike.baidu.com/item/%E6%A0%87%E5%87%86%E5%8C%96%E6%AD%BB%E4%BA%A1%E6%AF%94)是被标化组实际死亡数与预期死亡数之比，用SMR表示。若SMR>1，表示被标化人群的死亡率高于标准组；反之，若SMR<1，表示被标化人群的死亡率低于标准组。标准化死亡比可反映某一人群与标准人群的人口死亡的相对水平。

## 动态数列及其指标分析

动态数列(Dynamic series)是一系列按时间顺序排列起来的统计指标(可以为绝对数，相对数或平均 数)，用以观察和比较该事物在时间上的变化和发展趋势。常用的动态数列分析指标有：绝对增长量、发展速度与增长速度、平均发展速度与平均增长速度。

### 绝对增长量

绝对增长量是只事物在一定时间增长的绝对值，可分为：

- 累计增长量，即特定时间段内的终末指标值与起始指标值之差；
- 逐年增长量，即以年为周期， 今年的指标值与去年的指标值之差。

### 发展速度与增长速度

发展速度与增长速度均为相对比，说明事物在一定时期的速度变化。发展速度表示报告期指标的水 平相当于基期水平的百分之多少或若干倍，根据基期的确定，对发展速度可以计算：

- 定基比：即报告期指标与基期指标之比；
- 环比：即报告期指标与其前一期指标之比。

### 平均发展速度与平均增长速度

平均发展速度是各环比发展速度的几何均数，说明某事物在一个较长时期中逐期(如逐年)平均发展 的程度。平均增长速度是各环比增长速度的平均数，说明某事物在一个较长时期中逐期平均增长的程度。以$a_0$表示基期指标; $a_n$为第n期指标，则其计算公式为：

$$\begin{aligned}
平均发展速度 & = \sqrt[n]{a_n/a_0}\\ \\
平均增长速度 & =  平均发展速度 - 1 \\ \\
& = \sqrt[n]{a_n/a_0} -1
\end{aligned}$$
